FROM apache/airflow:2.10.4-python3.12

USER root
RUN apt-get update -qq && apt-get install -y -qq --no-install-recommends \
    postgresql-client \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir psycopg2-binary==2.9.10
